---
version: "3"

services:
  recom:
    build:
      context: ./recom
    volumes:
      - ./recom:/app
    restart: always
    command: python main.py

  mail:
    build:
      context: ./mail
    volumes:
      - ./mail:/app
    restart: always
    command: python main.py
