version: "3"

services:
  game:
    build: 
      context: ./game
    volumes:
      - ./game:/app
    command: python main.py
  
  mail:
    build:
      context: ./mail
    volumes:
    - ./mail:/app
    command: python main.py